/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
       // TestCases tests = new TestCases(); // Initialize your test class
      Automate_post_on_linkedin linkedin=new Automate_post_on_linkedin();
      //bookmyshow book=new bookmyshow();

        //TODO: call your test case functions one after other here

       // tests.testCase01();
       linkedin.Post_on_LinkedIn();
     // book.bookshow();

        //END Tests


       // tests.endTest(); // End your test by clearning connections and closing browser
      
       linkedin.endTest();
     // book.endTest();
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
